@startuml
' control app.py
' entity Boggle
' control make_board
' user as participant
' boundary index.html
' database words
' boundary board.html
' entity board
' control read_dict
' control check_valid_word
' control find_from 
' control find

app.py -> Boggle : creates
Boggle -> B.read_dict 
B.read_dict --> app.py:words[]
' app.py <-- make_board :board[][]
user -> index.html: route /
user <-- index.html: instructions/start
index.html -> "/start-timer": sets pts & timer
"/start-timer" -> "game-start.html": route /boggle/start
"game-start.html" -> B.make_board
B.make_board --> "game-start.html"
user <-- "game-start.html": display game.html
user -> "game-start.html": drags across letters
"game-start.html" -> JS_event_hdlr: creates word
JS_event_hdlr -> "/submit_word" : check_valid_word
"/submit_word"-> find: valid word
check_valid_word -->JS_event_hdlr:invalid reset scrn
find -> find_from
find_from --> find :yes or no
find -> score:+ if yes
find --> JS_event_hdlr:reset if no

@enduml