@startuml Remember Together - use cases 
skinparam actorStyle Hollow

"Loved ones" as LO
"Officiant" as Of
"Funeral director" as Admin
"Staff" as staff
"Immediate family" as mod 


' "Admin the app" as (admin)
"Setup users" as (setupUsers)
"Setup/mod zoom & board" as (z_setup)
"Zoom Service" as (zoom)
"Memorial board" as (board)
"Facebook" as (fb)
"Live Chat" as (chat)
"Instagram" as (insta)

' LO <-- (board)
' LO --> (zoom) 
LO --> (board)

(zoom) --> (chat)

Of --> (board)
' Of <-- (board)


(zoom) <-- (board)
(board) --> (fb)
(board) <-- (fb)
(board) --> (insta)
(board) <-- (insta)
(z_setup) --> (board)


' Admin --> (admin)

Admin --> (setupUsers)
' (admin) --> (board)
' (admin) <-- (board)
(setupUsers) --> LO
(setupUsers) --> Of
(setupUsers) --> staff
(setupUsers) --> mod

Admin --> (z_setup)
staff --> (z_setup)
mod --> (z_setup)


@enduml